name: 'Pypi upload'
description: 'Uplaod package to pypi'
author: 'Oscar Ortega'
inputs:
  user:
    description: PyPI user
    required: false
    default: __token__
  password:
    description: Password for your PyPI user or an access token
    required: true
  repository_url:
    description: The repository URL to use
    required: false
  packages_dir:
    description: The target directory for distribution
    required: false
    default: dist
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'code'
  color: 'yellow'